# Generated by Django 3.2.9 on 2021-12-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0002_rename_last_family_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='personinfo.person'),
        ),
    ]
